config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'about', to: 'home#about'

  resources :articles
  resources :categories
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'

  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories, dependent: :destroy
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }, uniqueness: true
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories, dependent: :destroy
  has_many :articles, through: :article_categories
  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase } # Enforces all email addresses to low cases
  validates :username, presence: true, length: { minimum: 3, maximum: 25 }, uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX, message: 'Invalid email format' }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :signed_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in?
    !!current_user
  end

  def require_user
    unless signed_in?
      flash[:danger] = 'You must be sign in to perform that action'
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit update show destroy]
  before_action :require_user, except: %i[index show]
  before_action :require_same_user, only: %i[edit update destroy]
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def edit; end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article was successfully updated'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def new
    @article = Article.new
  end

  def create
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = 'Article was created successfully'
      redirect_to article_path(@article)
    else
      render 'new'

    end
  end

  def show; end

  def destroy
    @article.destroy
    flash[:danger] = 'Article was successfully deleted'
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:danger] = 'You can only edit or delete your own articles'
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: %i[index show]
  before_action :set_category, only: %i[show edit update destroy]
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Category created successfully'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:success] = 'Category name was successfully updated'
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    flash[:danger] = 'Category was successfully deleted'
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def require_admin
    if !signed_in? || (signed_in? & !current_user.admin?)
      flash[:danger] = 'Only admins can perform that action'
      redirect_to categories_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to articles_path if signed_in?
  end

  def about; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    # render plain: params
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'Sign in succeed'
      redirect_to user_path(user)
    else
      flash.now[:danger] = 'Email or password is incorrect'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have signed out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update show destroy]
  before_action :require_user, except: %i[index show create new]
  before_action :require_same_user, only: %i[edit update]
  before_action :require_admin, only: [:destroy]
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Open blog #{@user.username}"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = 'Your account was updated successfully'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user.destroy unless @user.admin?
    flash[:danger] = "User #{@user.username} has been removed and all of articles he/she created also have been removed"
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = 'You can only edit or delete your own profile'
      redirect_to root_path
    end
  end

  def require_admin
    if signed_in? && !current_user.admin?
      flash[:danger] = 'Only admin users can perform this action'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: 'rounded mr-3')
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class="card-columns">
  <% obj.each do |article| %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= link_to article.title, article_path(article.id) %></h5>
      <p class="card-text"><%= simple_format(article.description) %></p>
      <% if article.categories.any? %>
        <p>Categories: <%= render article.categories %></p>
      <% end %>
      <p class="card-text d-flex justify-content-between">
        <small class="text-muted"><%= article.user.username %></small>
        <small class="text-muted"><%= time_ago_in_words(article.updated_at.strftime("%H:%M:%S, %B %d, %Y")).capitalize %> ago</small>
      </p>
    </div>
    <% if signed_in? && (article.user == current_user || current_user.admin?) %>
      <div class="card-footer d-flex justify-content-between">
        <%= link_to "Edit", edit_article_path(article), :class => "btn btn-sm btn-primary" %>
        <%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"}, :class => "btn btn-sm btn-danger" %>
      </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<%= form_for @article do |f| %>
  <div class="mb-3">
    <%= f.label :title, :class => "form-label" %>
    <%= f.text_field :title, :class => "form-control", autofocus: true, placeholder: "Title of an article" %>
  </div>
  <div class="mb-3">
    <%= f.label :description, :class => "form-label" %>
    <%= f.text_area :description, :class => "form-control", :rows => "5", placeholder: "Description" %>
  </div>
  <div class="mb-3">
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <div class="form-check form-check-inline">
        <%= cb.check_box(class: "form-check-input") %>
        <%= cb.label(class: "form-check-label") %>
      </div>
    <% end %>
  </div>
  <%= f.submit :class => "btn btn-primary" %>
  <%= link_to "Cancel", articles_path, class: "btn btn-secondary" %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<div>
  <% if signed_in? %>
    <%= link_to "+ Create a new article", new_article_path, :class => "btn btn-success mb-3" %>
  <% end %>

</div>
<div class="d-flex justify-content-center">
  <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>
</div>
<%= render 'article', obj: @articles %>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center"><%= @article.title %></h2>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Author: <%= link_to @article.user.username, user_path(@article.user) %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= @article.created_at.strftime("%H:%M:%S, %B %d, %Y") %></h6>
    <p class="card-text"><%= simple_format(@article.description) %></p>
    <% if @article.categories.any? %>
      <p>Categories: <%= render @article.categories %></p>
    <% end %>
    <% if signed_in? && @article.user == current_user %>
      <%= link_to "Edit", edit_article_path, :class => "btn btn-primary btn-sm" %>
      <%= link_to "Delete", article_path, method: :delete, data: {confirm: "are you sure you want to delete the article?"}, :class => "btn btn-danger btn-sm" %>
      <%= link_to "Back", articles_path, :class => "btn btn-secondary btn-sm" %>
    <% end %>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge badge-info"><%= link_to category.name, category_path(category), class: "text-white" %></span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for @category do |f| %>
  <div class="mb-3">
    <%= f.label :name, :class => "form-label" %>
    <%= f.text_field :name, :class => "form-control", autofocus: true, placeholder: "Category name" %>
  </div>
  <%= f.submit :class => "btn btn-primary" %>
  <%= link_to "Cancel", categories_path, class: 'btn btn-secondary' %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>All categories (<%= Category.all.length %>)</h1>
<%= will_paginate(@categories, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>
<ul class="list-group">
  <% @categories.each do |category| %>
    <li class="list-group-item d-flex justify-content-between">
      <div class="">
        <%= link_to category.name, category_path(category) %>
        <small class="ml-2"><%= pluralize(category.articles.count, "article") %></small>
      </div>
      <% if signed_in? && current_user.admin? %>
        <div class="btn-group">
          <%= link_to "Edit", edit_category_path(category), class: "btn btn-primary btn-sm" %>
          <%= link_to "Delete", category_path(category), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-sm" %>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<h1>Create a new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="d-flex">
  <p><%= @category.name %> (<%= pluralize(@category.articles.count, "article") %>)</p>
  <% if signed_in? && current_user.admin? %>
    <div class="ml-auto">
      <%= link_to "Edit", edit_category_path, class: "btn btn-primary" %>
    </div>
  <% end %>
</h1>
<div class="d-flex justify-content-center">
  <%= will_paginate(@category_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>
</div>
<%= render 'articles/article', obj: @category.articles %>

<%= link_to "Back to articles", articles_path, class: "btn btn-secondary mt-2" %>

app/views/home/about.html.erb
<h1>About page</h1>

app/views/home/index.html.erb
<div class="p-3">
  <h1 class="text-center my-5">Welcome to Open blog </h1>
  <div class="w-100 d-flex justify-content-center">
    <%= image_tag "banner.svg", :style => "width: 50%;" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-dark">
  <div class="container d-flex justify-content-between">
    <div class="text-muted">Copyright &copy; 2021 <span class="text-white">Open blog</span> by <%= link_to "Instriation", "https://instriation.com", target: "_blank" %></div>
    <div class="text-muted">
      <%= link_to "About", about_path %>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %> alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Open blog", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 mr-auto">
        <li class="nav-item">
          <%= link_to "Articles", articles_path, :class => "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, :class => "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Category
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if signed_in? && current_user.admin? %>
              <%= link_to "+ New category", new_category_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
            <% end %>
            <%= link_to "All categories", categories_path, class: "dropdown-item" %>
            <% Category.all.each do |category| %>
              <%= link_to category.name, category_path(category), class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
      </ul>
      <% if signed_in? %>
        <p class="text-white my-auto mr-3">Welcome <%= current_user.admin? ? " admin!" : current_user.username + "!" %></p>
        <%= link_to "Sign out", signout_path, :class => "btn btn-outline-success mr-3", :method => :delete %>
        <%= link_to "Profile", user_path(current_user), :class => "btn btn-outline-success" %>
      <% else %>
        <%= link_to "Sign in", signin_path, :class => "btn btn-outline-success mr-3" %>
        <%= link_to "Sign up", signup_path, :class => "btn btn-outline-success" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Open blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column h-100">
    <%= render 'layouts/navbar' %>
    <div class="container p-3">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <% if Rails.env.development? %>
      <div class="alert alert-secondary mt-auto">
        <%= debug(params)%>
      </div>
    <% end %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="alert alert-danger">
        <div class="alert-title">
          <%= pluralize(obj.errors.count, "error") %> prohibited from being saved:
        </div>
        <div class="alert-body">
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_for @user do |f| %>
  <div class="mb-3">
    <%= f.label :username, :class => "form-label" %>
    <%= f.text_field :username, :class => "form-control", autofocus: true, placeholder: "Username" %>
  </div>
  <div class="mb-3">
    <%= f.label :email, :class => "form-label" %>
    <%= f.email_field :email, :class => "form-control", placeholder: "Email" %>
  </div>
  <div class="mb-3">
    <%= f.label :password, :class => "form-label" %>
    <%= f.password_field :password, :class => "form-control", placeholder: "Enter password" %>
  </div>
  <%= f.submit (@user.new_record? ? "Sign up" : "Update"), :class => "btn btn-primary" %>
  <% if signed_in? %>
    <%= link_to "Cancel", user_path(@user), :class => "btn btn-secondary" %>
  <% else %>
    <%= link_to "Sign in", signin_path, :class => "btn btn-success" %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>All bloggers</h1>
<div class="d-flex justify-content-center">
  <%= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>
</div>
<% @users.each do |user| %>
  <div class="media mb-3">
    <%= gravatar_for(user) %>
    <div class="media-body">
      <h5 class="mt-0 d-flex justify-content-between">
        <p>
          <%= link_to user.username, user_path(user) %>
          <% if user.admin? %>
            <span class="badge badge-sm badge-success ml-2">Admin</span>
          <% end %>
        </p>
        <small class="text-muted">Member since: <%= user.created_at.strftime("%B %d, %Y") %></small>
      </h5>
      <div class="d-flex justify-content-between">
        <div><%= user.email %></div>
        <div class="d-flex">
          <% if signed_in? && current_user == user %>
            <%= link_to "Edit", edit_user_path(user), :class => "btn btn-sm btn-primary mr-3" %>
          <% end %>
          <% if signed_in? && current_user.admin? && !user.admin? %>
            <%= link_to "Remove", user_path(user), :class => "btn btn-sm btn-danger", data: {confirm: "Are you sure to remove this user?"}, method: :delete %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up to Open blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1>Profile - <%= @user.username %></h1>

<div class="media mb-3">
  <%= gravatar_for(@user) %>
  <div class="media-body">
    <h5 class="mt-0 d-flex justify-content-between">
      <p><%= @user.username %></p>
      <small class="text-muted">Member since: <%= @user.created_at.strftime("%B %d, %Y") %></small>
    </h5>
    <div class="d-flex">
      <div><%= @user.email %></div>
      <% if signed_in? && current_user == @user %>
        <div class="ml-auto">
          <%= link_to "Edit profile", edit_user_path(@user) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<h4><%= @user.username %>'s articles (<%= @user.articles.length %>)</h4>
<div class="d-flex justify-content-center">
  <%= will_paginate(@user_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>
</div>
<%= render 'articles/article', obj: @user_articles %>